# vim: set fileencoding=utf-8
"""
pythoneda/runtime/secrets/application/boot_app.py

This file defines the SecretsApp class.

Copyright (C) 2024-today boot's pythoneda-runtime/secrets-application

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.shared.application import PythonEDA


class SecretsApp(PythonEDA):
    """
    Runs PythonEDA Secrets.

    Class name: SecretsApp

    Responsibilities:
        - Runs PythonEDA Secrets.

    Collaborators:
        - Command-line handlers from pythoneda-runtime/secrets-infrastructure
    """

    def __init__(self):
        """
        Creates a new SecretsApp instance.
        """
        # boot_banner is automatically generated by pythoneda-runtime-def/secrets-application
        try:
            from pythoneda.runtime.secrets.application.secrets_banner import (
                SecretsBanner,
            )

            banner = SecretsBanner()
        except ImportError:
            banner = None
        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(SecretsApp.main("pythoneda.runtime.secrets.Secrets"))

# vim: syntax=python ts=4 sw=4 sts=4 tw=79 sr et
# Local Variables:
# mode: python
# python-indent-offset: 4
# tab-width: 4
# indent-tabs-mode: nil
# fill-column: 79
# End:
